POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Determination leads to success",
  "author": "Z",
  "url": "https://microsoft.com/",
  "likes": 10,
  "user": "64a4361f683a00efe6ea0d24"
}