DELETE http://localhost:3003/api/blogs/64a46f75429423ea8cb09674
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InpoaSIsImlkIjoiNjRhNDM2MWY2ODNhMDBlZmU2ZWEwZDI0IiwiaWF0IjoxNjg4NTAwNDEyLCJleHAiOjE2ODg1MDQwMTJ9.C1ieNjsM4m4QN_rlGGfuc1tYiwiWOrkUGpZ7Qj3_oCY
